package cn.timelost.hr.pojo;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

/**
 * @TableName department
 */
@Data
public class Department implements Serializable {
    /**
     * 部门编号
     *
     * @mbg.generated Sun Jan 24 21:46:43 CST 2021
     */
    private Integer id;

    /**
     * 部门名称
     *
     * @mbg.generated Sun Jan 24 21:46:43 CST 2021
     */
    private String departmentName;

    /**
     * 描述
     *
     * @mbg.generated Sun Jan 24 21:46:43 CST 2021
     */
    private String description;

    /**
     * 
     *
     * @mbg.generated Sun Jan 24 21:46:43 CST 2021
     */
    private Date createTime;

    /**
     * 
     *
     * @mbg.generated Sun Jan 24 21:46:43 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Sun Jan 24 21:46:43 CST 2021
     */
    private static final long serialVersionUID = 1L;
}