package cn.timelost.hr.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;

/**
 * @TableName personal_salary
 */
@Data
public class PersonalSalary implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private Integer id;

    /**
     * 员工编号
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private Integer personalId;

    /**
     * 员工姓名
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private String personalName;

    /**
     * 部门名称
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private String departmentName;

    /**
     * 岗位名称
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private String positionName;

    /**
     * 日期
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private Date salaryDate;

    /**
     * 基本工资
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private BigDecimal basisSalary;

    /**
     * 补助工资
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private BigDecimal subsidySalary;

    /**
     * 社保
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private BigDecimal socialSalary;

    /**
     * 公积金
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private BigDecimal providentFund;

    /**
     * 奖金
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private BigDecimal bonus;

    /**
     * 应发工资
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private BigDecimal allSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personal_salary
     *
     * @mbg.generated Sun Feb 07 09:47:18 CST 2021
     */
    private static final long serialVersionUID = 1L;
}