package cn.timelost.hr.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

/**
 * @TableName personal_train
 */
@Data
public class PersonalTrain implements Serializable {
    /**
     * 
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private Integer id;

    /**
     * 员工id
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private Integer personalId;

    /**
     * 员工姓名
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private String personalName;

    /**
     * 部门名称
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private String departmentName;

    /**
     * 岗位名称
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private String positionName;

    /**
     * 开始培训日期
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    @JsonFormat(
            pattern = "yyyy-MM-dd",
            timezone = "GMT+8"
    )
    private Date beginDate;

    /**
     * 结束培训日期
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    @JsonFormat(
            pattern = "yyyy-MM-dd",
            timezone = "GMT+8"
    )
    private Date endDate;

    /**
     * 培训内容
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private String trainContent;

    /**
     * 培训分数
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private BigDecimal trainScore;

    /**
     * 费用
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private BigDecimal trainCost;

    /**
     * 备注
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private String remake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personal_train
     *
     * @mbg.generated Tue Feb 02 16:19:36 CST 2021
     */
    private static final long serialVersionUID = 1L;
}