package cn.timelost.hr.pojo;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName personal
 */
@Data
public class Personal implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Integer id;

    /**
     * 姓名
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private String name;

    /**
     * 性别 1:男 2：女
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Integer gender;

    /**
     * 出生日期
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Date birthday;

    /**
     * 联系电话
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Long phone;

    /**
     * 邮箱
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private String email;

    /**
     * 身份证号
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Long identity;

    /**
     * 学历
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private String education;

    /**
     * 毕业学校
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private String school;

    /**
     * 照片url
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private String imgUrl;

    /**
     * 工作状态：1:正式 2:试用 3:实习 4:离职
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Integer workStatus;

    /**
     * 部门id
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Integer departmentId;

    /**
     * 职位id
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Integer positionId;

    /**
     * 入职时间
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Date beginDate;

    /**
     * 
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Date createTime;

    /**
     * 
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personal
     *
     * @mbg.generated Sun Jan 31 10:13:20 CST 2021
     */
    private static final long serialVersionUID = 1L;
}