package cn.timelost.hr.pojo;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName personal_reward
 */
@Data
public class PersonalReward implements Serializable {
    /**
     * 
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private Integer id;

    /**
     * 员工编号
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private Integer personalId;

    /**
     * 员工姓名
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private String personalName;

    /**
     * 部门名称
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private String departmentName;

    /**
     * 职位名称
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private String positionName;

    /**
     * 日期
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private Date rewardDate;

    /**
     * 奖罚种类 1：奖励 2：惩罚
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private Integer rewardKind;

    /**
     * 金额
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private Long rewardAmount;

    /**
     * 奖罚描述
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personal_reward
     *
     * @mbg.generated Thu Feb 04 11:56:02 CST 2021
     */
    private static final long serialVersionUID = 1L;
}