package cn.timelost.hr.pojo;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName recruitment
 */
@Data
public class Recruitment implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private Integer id;

    /**
     * 招聘部门
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private String departmentName;

    /**
     * 招聘职位
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private String positionName;

    /**
     * 需求人数
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private Integer needNum;

    /**
     * 招聘内容
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private String demand;

    /**
     * 学历要求
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private String needEducation;

    /**
     * 发布日期
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private Date startDate;

    /**
     * 结束日期
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private Date endTime;

    /**
     * 状态  1:进行中 2：已完成
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private Integer recruitStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recruitment
     *
     * @mbg.generated Sun Feb 07 19:20:23 CST 2021
     */
    private static final long serialVersionUID = 1L;
}