version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven_ehr
        displayName: Maven 构建
        jdkVersion: 8
        mavenVersion: 3.3.9
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT_EHR
            path:
              - ./target
        caches:
          - ~/.m2
        strategy: {}
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: deploy@agent
        name: ehr
        displayName: 主机部署
        hostGroupID:
          ID: HW
          hostID:
            - 67389865-f116-409f-bc74-7ec14580c8a3
        deployArtifact:
          - source: build
            name: ehr
            target: ~/gitee_go/deploy
            dependArtifact: BUILD_ARTIFACT_EHR
        script:
          - '#!/bin/sh'
          - echo "开始执行shell脚本"
          - ''
          - tar zxvf ~/gitee_go/deploy/ehr.tar.gz -C /root/gitee_go/deploy
          - ''
          - '# 指定jenkins中存放编译好的jar的位置'
          - JENKINS_JAR_PATH=/root/gitee_go/deploy/target
          - ''
          - '# 指定jenkins中存放编译好的jar的名称(这个jar的名字和pom文件配置有关)'
          - JENKINS_JAR_NAME=hr-0.0.1-SNAPSHOT.jar
          - ''
          - '# 获取该项目的进程号，用于重新部署项目前杀死进程'
          - process_id=$(ps -ef | grep hr | grep -v "grep" | awk '{print $2}')
          - ''
          - '# 如果该项目正在运行，就杀死项目进程'
          - if [[ ! -z "$process_id" ]]
          - then
          - echo "停止服务"
          - kill -9 $process_id
          - else
          - echo "服务未启动"
          - fi
          - ''
          - '# 进入Jenkins中编译好的jar的位置'
          - cd ${JENKINS_JAR_PATH}
          - ''
          - '# 后台启动项目，并且将控制台日志输出到nohup.out中'
          - nohup /usr/bin/java -jar ${JENKINS_JAR_NAME} --server.port=9003 -Dfile.encoding=UTF-8 >nohup.out &
          - ''
          - echo "shell脚本执行完毕"
        notify: []
        strategy:
          retry: '0'
